# =============================================================================
# Arty S7-50 Platform - CMake Configuration
# =============================================================================
# Xilinx XC7S50 FPGA - Vivado TCL-based build
# Uses VexRiscvJtag (with hardware JTAG TAP for debugging)
# =============================================================================

message(STATUS "Configuring for Arty S7-50 (Xilinx XC7S50)")

# Platform-specific settings
set(FPGA_PART "xc7s50csga324-1")
set(TOP_MODULE "arty_s7_spi_copter_top")
set(SYSTEM_CLOCK_HZ 72000000)  # 72 MHz system clock

# Platform-specific sources
set(PLATFORM_SOURCES
    ${CMAKE_SOURCE_DIR}/ArtS7-50/arty_s7_spi_copter_top.v
)

# Constraints
set(CONSTRAINTS_FILE ${CMAKE_SOURCE_DIR}/ArtS7-50/Arty-S7-50-Master.xdc)

# Output files
set(BITSTREAM ${BUILD_DIR}/arty_s7_spi_copter.bit)

# All RTL sources
set(ALL_SOURCES ${RTL_SOURCES} ${PLATFORM_SOURCES})

# Firmware file
set(FIRMWARE_MEM_SRC ${CMAKE_SOURCE_DIR}/firmware/firmware.mem)

# -----------------------------------------------------------------------------
# Find Vivado
# -----------------------------------------------------------------------------
find_program(VIVADO vivado
    HINTS
    $ENV{XILINX_VIVADO}/bin
    /opt/Xilinx/Vivado/2023.2/bin
    /opt/Xilinx/Vivado/2024.1/bin
    /tools/Xilinx/Vivado/2023.2/bin
)

if(NOT VIVADO)
    message(WARNING "Vivado not found. Source Vivado settings first:")
    message(WARNING "  source /opt/Xilinx/Vivado/2023.2/settings64.sh")
endif()

# -----------------------------------------------------------------------------
# Generate Vivado TCL Build Script
# -----------------------------------------------------------------------------
set(VIVADO_TCL ${BUILD_DIR}/build_artys7.tcl)

# Create list of source files for TCL
set(TCL_SOURCE_LIST "")
foreach(src ${ALL_SOURCES})
    set(TCL_SOURCE_LIST "${TCL_SOURCE_LIST}    ${src}\n")
endforeach()

file(WRITE ${VIVADO_TCL} "# =============================================================================
# Arty S7-50 Vivado Build Script (Auto-generated by CMake)
# =============================================================================
# Run with: vivado -mode batch -source build_artys7.tcl
# =============================================================================

set project_name \"SPICopterArtyS7\"
set part \"${FPGA_PART}\"
set top_module \"${TOP_MODULE}\"
set output_dir \"${BUILD_DIR}\"

# Create project (in memory, non-project mode)
create_project -in_memory -part \$part

# Add source files
set sources {
${TCL_SOURCE_LIST}}

foreach src \$sources {
    if {\$src ne \"\"} {
        add_files -norecurse \$src
    }
}

# Add constraints
add_files -fileset constrs_1 -norecurse ${CONSTRAINTS_FILE}

# Set top module
set_property top \$top_module [current_fileset]

# Update compile order
update_compile_order -fileset sources_1

# Synthesis
puts \"Running Synthesis...\"
synth_design -top \$top_module -part \$part

# Write checkpoint
write_checkpoint -force \$output_dir/post_synth.dcp

# Report utilization
report_utilization -file \$output_dir/utilization_synth.rpt

# Implementation
puts \"Running Implementation...\"
opt_design
place_design
route_design

# Write checkpoint
write_checkpoint -force \$output_dir/post_route.dcp

# Reports
report_utilization -file \$output_dir/utilization_impl.rpt
report_timing_summary -file \$output_dir/timing_summary.rpt

# Generate bitstream
puts \"Generating Bitstream...\"
write_bitstream -force \$output_dir/arty_s7_spi_copter.bit

puts \"Build complete!\"
puts \"Bitstream: \$output_dir/arty_s7_spi_copter.bit\"
")

message(STATUS "  Vivado TCL: ${VIVADO_TCL}")
message(STATUS "  Top module: ${TOP_MODULE}")
message(STATUS "  VexRiscv: VexRiscvJtag.v (with JTAG TAP)")

# -----------------------------------------------------------------------------
# Bitstream Target
# -----------------------------------------------------------------------------
if(VIVADO)
    add_custom_command(
        OUTPUT ${BITSTREAM}
        COMMAND ${VIVADO} -mode batch -source ${VIVADO_TCL}
        DEPENDS ${ALL_SOURCES} ${CONSTRAINTS_FILE} ${FIRMWARE_MEM_SRC}
        WORKING_DIRECTORY ${BUILD_DIR}
        COMMENT "Building Arty S7-50 bitstream with Vivado..."
        VERBATIM
    )
    
    add_custom_target(bitstream
        DEPENDS ${BITSTREAM}
        COMMENT "Arty S7-50 bitstream complete"
    )
else()
    add_custom_target(bitstream
        COMMAND ${CMAKE_COMMAND} -E echo ""
        COMMAND ${CMAKE_COMMAND} -E echo "ERROR: Vivado not found!"
        COMMAND ${CMAKE_COMMAND} -E echo "Run: source /opt/Xilinx/Vivado/2023.2/settings64.sh"
        COMMAND ${CMAKE_COMMAND} -E echo "Then reconfigure: cmake -B build -DPLATFORM=artys7"
        COMMAND ${CMAKE_COMMAND} -E echo ""
        COMMAND ${CMAKE_COMMAND} -E false
        COMMENT "Vivado required for Arty S7"
    )
endif()

# -----------------------------------------------------------------------------
# Upload Target (openFPGALoader or Vivado)
# -----------------------------------------------------------------------------
find_program(OPENFPGALOADER openFPGALoader)

if(OPENFPGALOADER)
    add_custom_target(upload
        COMMAND ${OPENFPGALOADER} -b arty_s7_50 ${BITSTREAM}
        DEPENDS bitstream
        COMMENT "Programming Arty S7-50..."
    )
else()
    add_custom_target(upload
        COMMAND ${CMAKE_COMMAND} -E echo ""
        COMMAND ${CMAKE_COMMAND} -E echo "Use Vivado Hardware Manager to program:"
        COMMAND ${CMAKE_COMMAND} -E echo "  Bitstream: ${BITSTREAM}"
        COMMAND ${CMAKE_COMMAND} -E echo ""
        COMMAND ${CMAKE_COMMAND} -E echo "Or install openFPGALoader:"
        COMMAND ${CMAKE_COMMAND} -E echo "  sudo apt install openfpgaloader"
        COMMAND ${CMAKE_COMMAND} -E echo ""
        COMMENT "Upload instructions"
    )
endif()

# -----------------------------------------------------------------------------
# Stats Target
# -----------------------------------------------------------------------------
add_custom_target(stats
    COMMAND ${CMAKE_COMMAND} -E echo "Utilization: ${BUILD_DIR}/utilization_impl.rpt"
    COMMAND ${CMAKE_COMMAND} -E echo "Timing: ${BUILD_DIR}/timing_summary.rpt"
    COMMAND cat ${BUILD_DIR}/utilization_impl.rpt 2>/dev/null || echo "Run bitstream target first"
    COMMENT "Arty S7-50 resource utilization"
)

# -----------------------------------------------------------------------------
# Check VexRiscvJtag.v exists
# -----------------------------------------------------------------------------
if(NOT EXISTS ${CMAKE_SOURCE_DIR}/src/cpu/VexRiscvJtag.v)
    message(WARNING "VexRiscvJtag.v not found!")
    message(WARNING "Generate with: cmake --build build --target generate-cpu")
endif()
