# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/docs/Arty-S7-50-Master.xdc

# Block Designs: bd/riscv_54mhz/riscv_54mhz.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_54mhz || ORIG_REF_NAME==riscv_54mhz} -quiet] -quiet

# IP: bd/riscv_54mhz/ip/riscv_54mhz_proc_sys_reset_0_0/riscv_54mhz_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_54mhz_proc_sys_reset_0_0 || ORIG_REF_NAME==riscv_54mhz_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_0/riscv_54mhz_microblaze_riscv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_54mhz_microblaze_riscv_0_0 || ORIG_REF_NAME==riscv_54mhz_microblaze_riscv_0_0} -quiet] -quiet

# IP: bd/riscv_54mhz/ip/riscv_54mhz_dlmb_v10_0/riscv_54mhz_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_54mhz_dlmb_v10_0 || ORIG_REF_NAME==riscv_54mhz_dlmb_v10_0} -quiet] -quiet

# IP: bd/riscv_54mhz/ip/riscv_54mhz_ilmb_v10_0/riscv_54mhz_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_54mhz_ilmb_v10_0 || ORIG_REF_NAME==riscv_54mhz_ilmb_v10_0} -quiet] -quiet

# IP: bd/riscv_54mhz/ip/riscv_54mhz_dlmb_bram_if_cntlr_0/riscv_54mhz_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_54mhz_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==riscv_54mhz_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/riscv_54mhz/ip/riscv_54mhz_ilmb_bram_if_cntlr_0/riscv_54mhz_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_54mhz_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==riscv_54mhz_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/riscv_54mhz/ip/riscv_54mhz_lmb_bram_0/riscv_54mhz_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_54mhz_lmb_bram_0 || ORIG_REF_NAME==riscv_54mhz_lmb_bram_0} -quiet] -quiet

# IP: bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/riscv_54mhz_microblaze_riscv_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_54mhz_microblaze_riscv_0_axi_periph_0 || ORIG_REF_NAME==riscv_54mhz_microblaze_riscv_0_axi_periph_0} -quiet] -quiet

# IP: bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_intc_0/riscv_54mhz_microblaze_riscv_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_54mhz_microblaze_riscv_0_axi_intc_0 || ORIG_REF_NAME==riscv_54mhz_microblaze_riscv_0_axi_intc_0} -quiet] -quiet

# IP: bd/riscv_54mhz/ip/riscv_54mhz_mdm_1_0/riscv_54mhz_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_54mhz_mdm_1_0 || ORIG_REF_NAME==riscv_54mhz_mdm_1_0} -quiet] -quiet

# IP: bd/riscv_54mhz/ip/riscv_54mhz_axi_uartlite_0_0/riscv_54mhz_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_54mhz_axi_uartlite_0_0 || ORIG_REF_NAME==riscv_54mhz_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/riscv_54mhz/ip/riscv_54mhz_arty_s7_spi_copter_t_0_0/riscv_54mhz_arty_s7_spi_copter_t_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_54mhz_arty_s7_spi_copter_t_0_0 || ORIG_REF_NAME==riscv_54mhz_arty_s7_spi_copter_t_0_0} -quiet] -quiet

# IP: bd/riscv_54mhz/ip/riscv_54mhz_axi_esc_uart_0_0/riscv_54mhz_axi_esc_uart_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_54mhz_axi_esc_uart_0_0 || ORIG_REF_NAME==riscv_54mhz_axi_esc_uart_0_0} -quiet] -quiet

# IP: bd/riscv_54mhz/ip/riscv_54mhz_clk_wiz_0_1/riscv_54mhz_clk_wiz_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_54mhz_clk_wiz_0_1 || ORIG_REF_NAME==riscv_54mhz_clk_wiz_0_1} -quiet] -quiet

# IP: bd/riscv_54mhz/ip/riscv_54mhz_axi_gpio_0_0/riscv_54mhz_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==riscv_54mhz_axi_gpio_0_0 || ORIG_REF_NAME==riscv_54mhz_axi_gpio_0_0} -quiet] -quiet

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/riscv_54mhz_ooc.xdc
