# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.runs/synth_1/riscv_54mhz_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
set_msg_config -id {HDL-1065} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7s50csga324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.cache/wt [current_project]
set_property parent.project_path /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {/home/tcmichals/harddrive/tools/AMD/vivado-boards/new} [current_project]
set_property board_part digilentinc.com:arty-s7-50:part0:1.1 [current_project]
set_property ip_output_repo /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/hdl/riscv_54mhz_wrapper.v
add_files /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.srcs/sources_1/bd/riscv_54mhz/riscv_54mhz.bd
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_proc_sys_reset_0_0/riscv_54mhz_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_proc_sys_reset_0_0/riscv_54mhz_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_0/riscv_54mhz_microblaze_riscv_0_0.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_0/riscv_54mhz_microblaze_riscv_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_0/riscv_54mhz_microblaze_riscv_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_dlmb_v10_0/riscv_54mhz_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_ilmb_v10_0/riscv_54mhz_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_dlmb_bram_if_cntlr_0/riscv_54mhz_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_ilmb_bram_if_cntlr_0/riscv_54mhz_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_lmb_bram_0/riscv_54mhz_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_1/bd_8fe5_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_2/bd_8fe5_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_3/bd_8fe5_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_4/bd_8fe5_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_5/bd_8fe5_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_6/bd_8fe5_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_7/bd_8fe5_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_8/bd_8fe5_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_9/bd_8fe5_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_10/bd_8fe5_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_11/bd_8fe5_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_12/bd_8fe5_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_13/bd_8fe5_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_14/bd_8fe5_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_15/bd_8fe5_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_16/bd_8fe5_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_20/bd_8fe5_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_21/bd_8fe5_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_22/bd_8fe5_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_23/bd_8fe5_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_24/bd_8fe5_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_25/bd_8fe5_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_26/bd_8fe5_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_27/bd_8fe5_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_28/bd_8fe5_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_29/bd_8fe5_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_30/bd_8fe5_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_31/bd_8fe5_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_33/bd_8fe5_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_34/bd_8fe5_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_35/bd_8fe5_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_36/bd_8fe5_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_37/bd_8fe5_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_38/bd_8fe5_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_40/bd_8fe5_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_41/bd_8fe5_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_42/bd_8fe5_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_43/bd_8fe5_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_44/bd_8fe5_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_45/bd_8fe5_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_47/bd_8fe5_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_48/bd_8fe5_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_49/bd_8fe5_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_50/bd_8fe5_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_51/bd_8fe5_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_52/bd_8fe5_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_intc_0/riscv_54mhz_microblaze_riscv_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_intc_0/riscv_54mhz_microblaze_riscv_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_intc_0/riscv_54mhz_microblaze_riscv_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_mdm_1_0/riscv_54mhz_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_mdm_1_0/riscv_54mhz_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_axi_uartlite_0_0/riscv_54mhz_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_axi_uartlite_0_0/riscv_54mhz_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_clk_wiz_0_1/riscv_54mhz_clk_wiz_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_clk_wiz_0_1/riscv_54mhz_clk_wiz_0_1.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_clk_wiz_0_1/riscv_54mhz_clk_wiz_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_axi_gpio_0_0/riscv_54mhz_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_axi_gpio_0_0/riscv_54mhz_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/riscv_54mhz_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_0/data/riscv_bootloop.elf]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.srcs/constrs_1/imports/docs/Arty-S7-50-Master.xdc
set_property used_in_implementation false [get_files /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.srcs/constrs_1/imports/docs/Arty-S7-50-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.srcs/utils_1/imports/synth_1/riscv_54mhz_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top riscv_54mhz_wrapper -part xc7s50csga324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef riscv_54mhz_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file riscv_54mhz_wrapper_utilization_synth.rpt -pb riscv_54mhz_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
