# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.srcs/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/riscv_54mhz_microblaze_riscv_0_axi_periph_0.xci
# IP: The module: 'riscv_54mhz_microblaze_riscv_0_axi_periph_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/bd_8fe5.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_1/bd_8fe5_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_2/bd_8fe5_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_3/bd_8fe5_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_4/bd_8fe5_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_5/bd_8fe5_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_6/bd_8fe5_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_7/bd_8fe5_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_8/bd_8fe5_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_9/bd_8fe5_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_10/bd_8fe5_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_11/bd_8fe5_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_12/bd_8fe5_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_13/bd_8fe5_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_14/bd_8fe5_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_15/bd_8fe5_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_16/bd_8fe5_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_17/bd_8fe5_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_18/bd_8fe5_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_19/bd_8fe5_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_20/bd_8fe5_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_21/bd_8fe5_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_22/bd_8fe5_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_23/bd_8fe5_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_24/bd_8fe5_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_25/bd_8fe5_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_26/bd_8fe5_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_27/bd_8fe5_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_28/bd_8fe5_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_29/bd_8fe5_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_30/bd_8fe5_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_31/bd_8fe5_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_32/bd_8fe5_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_33/bd_8fe5_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_34/bd_8fe5_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_35/bd_8fe5_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_36/bd_8fe5_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_37/bd_8fe5_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_38/bd_8fe5_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_39/bd_8fe5_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_40/bd_8fe5_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_41/bd_8fe5_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_42/bd_8fe5_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_43/bd_8fe5_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_44/bd_8fe5_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_45/bd_8fe5_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_46/bd_8fe5_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_47/bd_8fe5_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_48/bd_8fe5_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_49/bd_8fe5_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_50/bd_8fe5_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_51/bd_8fe5_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_52/bd_8fe5_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_53/bd_8fe5_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_1/bd_8fe5_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_2/bd_8fe5_arinsw_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_3/bd_8fe5_rinsw_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_4/bd_8fe5_awinsw_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_5/bd_8fe5_winsw_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_6/bd_8fe5_binsw_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_7/bd_8fe5_aroutsw_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_8/bd_8fe5_routsw_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_9/bd_8fe5_awoutsw_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_10/bd_8fe5_woutsw_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_11/bd_8fe5_boutsw_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_12/bd_8fe5_arni_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_13/bd_8fe5_rni_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_14/bd_8fe5_awni_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_15/bd_8fe5_wni_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_16/bd_8fe5_bni_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_20/bd_8fe5_s00a2s_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_21/bd_8fe5_sarn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_22/bd_8fe5_srn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_23/bd_8fe5_sawn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_24/bd_8fe5_swn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_25/bd_8fe5_sbn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_26/bd_8fe5_m00s2a_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_27/bd_8fe5_m00arn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_28/bd_8fe5_m00rn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_29/bd_8fe5_m00awn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_30/bd_8fe5_m00wn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_31/bd_8fe5_m00bn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_33/bd_8fe5_m01s2a_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_34/bd_8fe5_m01arn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_35/bd_8fe5_m01rn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_36/bd_8fe5_m01awn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_37/bd_8fe5_m01wn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_38/bd_8fe5_m01bn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_40/bd_8fe5_m02s2a_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_41/bd_8fe5_m02arn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_42/bd_8fe5_m02rn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_43/bd_8fe5_m02awn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_44/bd_8fe5_m02wn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_45/bd_8fe5_m02bn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_47/bd_8fe5_m03s2a_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_48/bd_8fe5_m03arn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_49/bd_8fe5_m03rn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_50/bd_8fe5_m03awn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_51/bd_8fe5_m03wn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_52/bd_8fe5_m03bn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscv_54mhz_microblaze_riscv_0_axi_periph_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscv_54mhz_microblaze_riscv_0_axi_periph_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.srcs/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/riscv_54mhz_microblaze_riscv_0_axi_periph_0.xci
# IP: The module: 'riscv_54mhz_microblaze_riscv_0_axi_periph_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/bd_8fe5.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_1/bd_8fe5_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_2/bd_8fe5_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_3/bd_8fe5_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_4/bd_8fe5_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_5/bd_8fe5_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_6/bd_8fe5_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_7/bd_8fe5_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_8/bd_8fe5_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_9/bd_8fe5_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_10/bd_8fe5_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_11/bd_8fe5_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_12/bd_8fe5_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_13/bd_8fe5_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_14/bd_8fe5_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_15/bd_8fe5_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_16/bd_8fe5_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_17/bd_8fe5_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_18/bd_8fe5_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_19/bd_8fe5_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_20/bd_8fe5_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_21/bd_8fe5_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_22/bd_8fe5_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_23/bd_8fe5_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_24/bd_8fe5_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_25/bd_8fe5_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_26/bd_8fe5_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_27/bd_8fe5_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_28/bd_8fe5_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_29/bd_8fe5_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_30/bd_8fe5_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_31/bd_8fe5_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_32/bd_8fe5_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_33/bd_8fe5_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_34/bd_8fe5_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_35/bd_8fe5_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_36/bd_8fe5_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_37/bd_8fe5_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_38/bd_8fe5_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_39/bd_8fe5_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_40/bd_8fe5_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_41/bd_8fe5_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_42/bd_8fe5_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_43/bd_8fe5_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_44/bd_8fe5_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_45/bd_8fe5_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_46/bd_8fe5_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_47/bd_8fe5_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_48/bd_8fe5_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_49/bd_8fe5_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_50/bd_8fe5_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_51/bd_8fe5_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_52/bd_8fe5_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_53/bd_8fe5_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_1/bd_8fe5_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_2/bd_8fe5_arinsw_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_3/bd_8fe5_rinsw_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_4/bd_8fe5_awinsw_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_5/bd_8fe5_winsw_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_6/bd_8fe5_binsw_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_7/bd_8fe5_aroutsw_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_8/bd_8fe5_routsw_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_9/bd_8fe5_awoutsw_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_10/bd_8fe5_woutsw_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_11/bd_8fe5_boutsw_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_12/bd_8fe5_arni_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_13/bd_8fe5_rni_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_14/bd_8fe5_awni_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_15/bd_8fe5_wni_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_16/bd_8fe5_bni_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_20/bd_8fe5_s00a2s_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_21/bd_8fe5_sarn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_22/bd_8fe5_srn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_23/bd_8fe5_sawn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_24/bd_8fe5_swn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_25/bd_8fe5_sbn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_26/bd_8fe5_m00s2a_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_27/bd_8fe5_m00arn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_28/bd_8fe5_m00rn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_29/bd_8fe5_m00awn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_30/bd_8fe5_m00wn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_31/bd_8fe5_m00bn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_33/bd_8fe5_m01s2a_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_34/bd_8fe5_m01arn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_35/bd_8fe5_m01rn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_36/bd_8fe5_m01awn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_37/bd_8fe5_m01wn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_38/bd_8fe5_m01bn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_40/bd_8fe5_m02s2a_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_41/bd_8fe5_m02arn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_42/bd_8fe5_m02rn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_43/bd_8fe5_m02awn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_44/bd_8fe5_m02wn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_45/bd_8fe5_m02bn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_47/bd_8fe5_m03s2a_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_48/bd_8fe5_m03arn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_49/bd_8fe5_m03rn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_50/bd_8fe5_m03awn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_51/bd_8fe5_m03wn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/bd_0/ip/ip_52/bd_8fe5_m03bn_0_ooc.xdc

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscv_54mhz_microblaze_riscv_0_axi_periph_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_microblaze_riscv_0_axi_periph_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscv_54mhz_microblaze_riscv_0_axi_periph_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
