# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.srcs/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_clk_wiz_0_1/riscv_54mhz_clk_wiz_0_1.xci
# IP: The module: 'riscv_54mhz_clk_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_clk_wiz_0_1/riscv_54mhz_clk_wiz_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscv_54mhz_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_clk_wiz_0_1/riscv_54mhz_clk_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscv_54mhz_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_clk_wiz_0_1/riscv_54mhz_clk_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscv_54mhz_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.srcs/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_clk_wiz_0_1/riscv_54mhz_clk_wiz_0_1.xci
# IP: The module: 'riscv_54mhz_clk_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_clk_wiz_0_1/riscv_54mhz_clk_wiz_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscv_54mhz_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_clk_wiz_0_1/riscv_54mhz_clk_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscv_54mhz_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /media/tcmichals/projects/Tang9K/HacksterIO/SPIQuadCopter/ArtS7-50/project/SPICopter/SPICopter.gen/sources_1/bd/riscv_54mhz/ip/riscv_54mhz_clk_wiz_0_1/riscv_54mhz_clk_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscv_54mhz_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
